train: ../train/images
val: ../valid/images
test: ../test/images

nc: 2
names: ['Paragraph', 'Table']

#roboflow:
#  workspace: invoice-extractor-a2oay
#  project: detecting-paragraph-and-table
#  version: 1
#  license: CC BY 4.0
#  url: https://universe.roboflow.com/invoice-extractor-a2oay/detecting-paragraph-and-table/dataset/1
